# name of the experiment
#  - will be present in the experiment name
experiment_name = "test_experiment"

# using the linux task-spooler (tsp).
nb_parallel_tasks = 4

# (absolute or relative) path to the instances file (csv)
# should contain the following columns:
#   - *path:* path to the instance (relative to the CSV file) 
#   - *time_limit:* time (in seconds) allowed to solve the instance
# any other column (including 'path' and 'time_limit') can be accessed in this configuration file
# by the %{COL_NAME} pattern
instance_filenames = "../../../dogs-pfsp/insts/test_taillard.csv"

# output prefix (where to create the result directory)
output_prefix = "."
# a "variable" "output_directory" will be created from the experiment_name and the output_prefix

# LIST OF AUTOMATICALLY CREATED VARIABLES
# %{experiment_name}  -> name of the experiment (defined in this file)
# %{path}             -> path to instance from the CSV file
# %{time_limit}       -> timelimit from the CSV file
# %{date}             -> %{YYYY}_%{MM}_%{DD}
# %{output_directory} -> %{output_prefix}/%{experiment_name}_%{date}/
# %{file_prefix}      -> %{output_directory}/%{exe_name+parameters}_%{subprograms+parameters}

############ LIST OF THE ALGORITHMS TO BE EXECUTED
# program to be executed and its parameters or sub-programs
[solvers]
    [solvers.ibs] # Iterative Beam Search algorithm
    exe_path = "../../dogs-pfsp/target/release/dogs-pfsp" # path to the exe (not a parameter)
    instance = "../../dogs-pfsp/insts/${path}"
    time     = "${time_limit}"
    perf     = "${file_prefix}.stats.json"
    solution = "${file_prefix}.sol"
        [solvers.ibs.f_flowtime] # flotime minimization sub-program
        guide = ["bound", "idle", "alpha"]